async function Module(moduleArg={}){var moduleRtn;var g=moduleArg,aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&"renderer"!=globalThis.process?.type;if(ca){const {createRequire:a}=await import("module");var require=a(import.meta.url)}var p=(a,b)=>{throw b;},da=import.meta.url,r="",ea,t;
if(ca){var fs=require("fs");da.startsWith("file:")&&(r=require("path").dirname(require("url").fileURLToPath(da))+"/");t=a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a)};ea=async a=>{a=w(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2);p=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{r=(new URL(".",da)).href}catch{}ba&&(t=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});ea=async a=>{if(w(a))return new Promise((c,
d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}var fa=console.log.bind(console),x=console.error.bind(console),B,C=!1,ha,w=a=>a.startsWith("file://"),ia,ja,D,E,F,G,H,I,J,K,L,ka,la=!1;
function ma(){var a=M.buffer;D=new Int8Array(a);F=new Int16Array(a);E=new Uint8Array(a);G=new Uint16Array(a);H=new Int32Array(a);I=new Uint32Array(a);J=new Float32Array(a);K=new Float64Array(a);L=new BigInt64Array(a);ka=new BigUint64Array(a)}function na(a){g.onAbort?.(a);a="Aborted("+a+")";x(a);C=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");ja?.(a);throw a;}var oa;
async function pa(a){if(!B)try{var b=await ea(a);return new Uint8Array(b)}catch{}if(a==oa&&B)a=new Uint8Array(B);else if(t)a=t(a);else throw"both async and sync fetching of the wasm failed";return a}async function qa(a,b){try{var c=await pa(a);return await WebAssembly.instantiate(c,b)}catch(d){x(`failed to asynchronously prepare wasm: ${d}`),na(d)}}
async function ra(a){var b=oa;if(!B&&!w(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){x(`wasm streaming compile failed: ${d}`),x("falling back to ArrayBuffer instantiation")}return qa(b,a)}class sa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var ta=a=>{for(;0<a.length;)a.shift()(g)},ua=[],va=[],wa=()=>{var a=g.preRun.shift();va.push(a)},xa=!0,N=a=>{for(var b="";;){var c=E[a++];if(!c)return b;b+=String.fromCharCode(c)}},Q={},R={},ya={},S=class extends Error{constructor(a){super(a);this.name="BindingError"}},za=a=>{throw new S(a);};
function Aa(a,b,c={}){var d=b.name;if(!a)throw new S(`type "${d}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(c.Ma)return;throw new S(`Cannot register type '${d}' twice`);}R[a]=b;delete ya[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(e=>e()))}function T(a,b,c={}){return Aa(a,b,c)}
var Ba=(a,b,c)=>{switch(b){case 1:return c?d=>D[d]:d=>E[d];case 2:return c?d=>F[d>>1]:d=>G[d>>1];case 4:return c?d=>H[d>>2]:d=>I[d>>2];case 8:return c?d=>L[d>>3]:d=>ka[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},Ca=a=>{throw new S(a.ia.la.ja.name+" instance already deleted");},Da=!1,Ea=()=>{},U=a=>{if(!globalThis.FinalizationRegistry)return U=b=>b,a;Da=new FinalizationRegistry(b=>{b=b.ia;--b.count.value;0===b.count.value&&(b.na?b.qa.ua(b.na):b.la.ja.ua(b.ka))});U=b=>
{var c=b.ia;c.na&&Da.register(b,{ia:c},b);return b};Ea=b=>{Da.unregister(b)};return U(a)},Fa=[];function Ga(){}
var Ja=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ka={},La=(a,b,c)=>{if(void 0===a[b].ma){var d=a[b];a[b]=function(...e){if(!a[b].ma.hasOwnProperty(e.length))throw new S(`Function '${c}' called with an invalid number of arguments (${e.length}) - expects one of (${a[b].ma})!`);return a[b].ma[e.length].apply(this,e)};a[b].ma=[];a[b].ma[d.xa]=d}},Ma=(a,b,c)=>{if(g.hasOwnProperty(a)){if(void 0===c||void 0!==g[a].ma&&void 0!==g[a].ma[c])throw new S(`Cannot register public name '${a}' twice`);La(g,
a,a);if(g[a].ma.hasOwnProperty(c))throw new S(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);g[a].ma[c]=b}else g[a]=b,g[a].xa=c},Na=a=>{a=a.replace(/[^a-zA-Z0-9_]/g,"$");var b=a.charCodeAt(0);return 48<=b&&57>=b?`_${a}`:a};function Oa(a,b,c,d,e,f,k,h){this.name=a;this.constructor=b;this.wa=c;this.ua=d;this.pa=e;this.Ka=f;this.Aa=k;this.Ja=h;this.Oa=[]}
var Pa=(a,b,c)=>{for(;b!==c;){if(!b.Aa)throw new S(`Expected null or instance of ${c.name}, got an instance of ${b.name}`);a=b.Aa(a);b=b.pa}return a},Qa=a=>{if(null===a)return"null";var b=typeof a;return"object"===b||"array"===b||"function"===b?a.toString():""+a};
function Ra(a,b){if(null===b){if(this.Da)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.ia)throw new S(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.ia.ka)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);return Pa(b.ia.ka,b.ia.la.ja,this.ja)}
function Sa(a,b){if(null===b){if(this.Da)throw new S(`null is not a valid ${this.name}`);if(this.Ca){var c=this.Pa();null!==a&&a.push(this.ua,c);return c}return 0}if(!b||!b.ia)throw new S(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.ia.ka)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(!this.Ba&&b.ia.la.Ba)throw new S(`Cannot convert argument of type ${b.ia.qa?b.ia.qa.name:b.ia.la.name} to parameter type ${this.name}`);c=Pa(b.ia.ka,b.ia.la.ja,this.ja);if(this.Ca){if(void 0===
b.ia.na)throw new S("Passing raw pointer to smart pointer is illegal");switch(this.Ra){case 0:if(b.ia.qa===this)c=b.ia.na;else throw new S(`Cannot convert argument of type ${b.ia.qa?b.ia.qa.name:b.ia.la.name} to parameter type ${this.name}`);break;case 1:c=b.ia.na;break;case 2:if(b.ia.qa===this)c=b.ia.na;else{var d=b.clone();c=this.Qa(c,Ta(()=>d["delete"]()));null!==a&&a.push(this.ua,c)}break;default:throw new S("Unsupporting sharing policy");}}return c}
function Ua(a,b){if(null===b){if(this.Da)throw new S(`null is not a valid ${this.name}`);return 0}if(!b.ia)throw new S(`Cannot pass "${Qa(b)}" as a ${this.name}`);if(!b.ia.ka)throw new S(`Cannot pass deleted object as a pointer of type ${this.name}`);if(b.ia.la.Ba)throw new S(`Cannot convert argument of type ${b.ia.la.name} to parameter type ${this.name}`);return Pa(b.ia.ka,b.ia.la.ja,this.ja)}function Va(a){return this.oa(I[a>>2])}
var Wa=(a,b,c)=>{if(b===c)return a;if(void 0===c.pa)return null;a=Wa(a,b,c.pa);return null===a?null:c.Ja(a)},Xa={},Ya=(a,b)=>{if(void 0===b)throw new S("ptr should not be undefined");for(;a.pa;)b=a.Aa(b),a=a.pa;return Xa[b]},Za=class extends Error{constructor(a){super(a);this.name="InternalError"}},$a=(a,b)=>{if(!b.la||!b.ka)throw new Za("makeClassHandle requires ptr and ptrType");if(!!b.qa!==!!b.na)throw new Za("Both smartPtrType and smartPtr must be specified");b.count={value:1};return U(Object.create(a,
{ia:{value:b,writable:!0}}))};function ab(a,b,c,d,e,f,k,h,n,m,l){this.name=a;this.ja=b;this.Da=c;this.Ba=d;this.Ca=e;this.Na=f;this.Ra=k;this.Ha=h;this.Pa=n;this.Qa=m;this.ua=l;e||void 0!==b.pa?this.ra=Sa:(this.ra=d?Ra:Ua,this.sa=null)}
var bb=(a,b,c)=>{if(!g.hasOwnProperty(a))throw new Za("Replacing nonexistent public symbol");void 0!==g[a].ma&&void 0!==c?g[a].ma[c]=b:(g[a]=b,g[a].xa=c)},V=(a,b)=>{a=N(a);var c=cb.get(b);if("function"!=typeof c)throw new S(`unknown function pointer with signature ${a}: ${b}`);return c};class db extends Error{}
var fb=a=>{a=eb(a);var b=N(a);W(a);return b},gb=(a,b)=>{function c(f){e[f]||R[f]||(ya[f]?ya[f].forEach(c):(d.push(f),e[f]=!0))}var d=[],e={};b.forEach(c);throw new db(`${a}: `+d.map(fb).join([", "]));},X=(a,b,c)=>{function d(h){h=c(h);if(h.length!==a.length)throw new Za("Mismatched type converter count");for(var n=0;n<a.length;++n)T(a[n],h[n])}a.forEach(h=>ya[h]=b);var e=Array(b.length),f=[],k=0;b.forEach((h,n)=>{R.hasOwnProperty(h)?e[n]=R[h]:(f.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(()=>
{e[n]=R[h];++k;k===f.length&&d(e)}))});0===f.length&&d(e)},hb=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(I[b+4*d>>2]);return c},ib=a=>{for(;a.length;){var b=a.pop();a.pop()(b)}};function jb(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].sa)return!0;return!1}
function kb(a,b,c,d,e,f){var k=b.length;if(2>k)throw new S("argTypes array size mismatch! Must at least get return value and 'this' types!");var h=null!==b[1]&&null!==c,n=jb(b);c=!b[0].Ga;var m=b[0],l=b[1];d=[a,za,d,e,ib,m.oa.bind(m),l?.ra.bind(l)];for(e=2;e<k;++e)m=b[e],d.push(m.ra.bind(m));if(!n)for(e=h?1:2;e<b.length;++e)null!==b[e].sa&&d.push(b[e].sa);n=jb(b);e=b.length-2;l=[];m=["fn"];h&&m.push("thisWired");for(k=0;k<e;++k)l.push(`arg${k}`),m.push(`arg${k}Wired`);l=l.join(",");m=m.join(",");
l=`return function (${l}) {\n`;n&&(l+="var destructors = [];\n");var q=n?"destructors":"null",y="humanName throwBindingError invoker fn runDestructors fromRetWire toClassParamWire".split(" ");h&&(l+=`var thisWired = toClassParamWire(${q}, this);\n`);for(k=0;k<e;++k){var u=`toArg${k}Wire`;l+=`var arg${k}Wired = ${u}(${q}, arg${k});\n`;y.push(u)}l+=(c||f?"var rv = ":"")+`invoker(${m});\n`;if(n)l+="runDestructors(destructors);\n";else for(k=h?1:2;k<b.length;++k)f=1===k?"thisWired":"arg"+(k-2)+"Wired",
null!==b[k].sa&&(l+=`${f}_dtor(${f});\n`,y.push(`${f}_dtor`));c&&(l+="var ret = fromRetWire(rv);\nreturn ret;\n");b=(new Function(y,l+"}\n"))(...d);return Ja(a,b)}
var lb=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},mb=[],Y=[0,1,,1,null,1,!0,1,!1,1],nb=a=>{9<a&&0===--Y[a+1]&&(Y[a]=void 0,mb.push(a))},pb=a=>{if(!a)throw new S(`Cannot use deleted val. handle = ${a}`);return Y[a]},Ta=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=mb.pop()||Y.length;Y[b]=a;Y[b+1]=1;return b}},qb={name:"emscripten::val",oa:a=>{var b=pb(a);nb(a);return b},ra:(a,b)=>Ta(b),ta:Va,sa:null},rb=(a,b)=>{switch(b){case 4:return function(c){return this.oa(J[c>>
2])};case 8:return function(c){return this.oa(K[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},sb=(a,b,c)=>{var d=E;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);if(127>=f){if(b>=c)break;d[b++]=f}else if(2047>=f){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(65535>=f){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;e++}}d[b]=0}},
tb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},ub=new TextDecoder,vb=(a,b,c,d)=>{c=b+c;if(d)return c;for(;a[b]&&!(b>=c);)++b;return b},wb=new TextDecoder("utf-16le"),xb=(a,b,c)=>{a>>=1;return wb.decode(G.subarray(a,vb(G,a,b/2,c)))},yb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)F[b>>1]=a.charCodeAt(e),b+=2;F[b>>1]=0;return b-d},zb=a=>2*a.length,Ab=(a,b,c)=>{var d=
"";a>>=2;for(var e=0;!(e>=b/4);e++){var f=I[a+e];if(!f&&!c)break;d+=String.fromCodePoint(f)}return d},Bb=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var f=a.codePointAt(e);65535<f&&e++;H[b>>2]=f;b+=4;if(b+4>c)break}H[b>>2]=0;return b-d},Cb=a=>{for(var b=0,c=0;c<a.length;++c)65535<a.codePointAt(c)&&c++,b+=4;return b},Db=0,Eb=[],Fb=a=>{var b=Eb.length;Eb.push(a);return b},Gb=(a,b)=>{for(var c=Array(a),d=0;d<a;++d){var e=d,f=I[b+4*d>>2],k=R[f];if(void 0===k)throw a=
`${`parameter ${d}`} has unknown type ${fb(f)}`,new S(a);c[e]=k}return c},Hb=(a,b,c)=>{var d=[];a=a(d,c);d.length&&(I[b>>2]=Ta(d));return a},Ib={},Jb=a=>{var b=Ib[a];return void 0===b?N(a):b},Z={},Kb=a=>{ha=a;xa||0<Db||(g.onExit?.(a),C=!0);p(a,new sa(a))},Lb=a=>{if(!C)try{if(a(),!(xa||0<Db))try{ha=a=ha,Kb(a)}catch(b){b instanceof sa||"unwind"==b||p(1,b)}}catch(b){b instanceof sa||"unwind"==b||p(1,b)}},Mb=[null,[],[]],Qb=(a,b,c,d)=>{var e={string:m=>{var l=0;if(null!==m&&void 0!==m&&0!==m){l=tb(m)+
1;var q=Nb(l);sb(m,q,l);l=q}return l},array:m=>{var l=Nb(m.length);D.set(m,l);return l}};a=g["_"+a];var f=[],k=0;if(d)for(var h=0;h<d.length;h++){var n=e[c[h]];n?(0===k&&(k=Ob()),f[h]=n(d[h])):f[h]=d[h]}c=a(...f);return c=function(m){0!==k&&Pb(k);return"string"===b?m?ub.decode(E.subarray(m,vb(E,m))):"":"boolean"===b?!!m:m}(c)};
(()=>{let a=Ga.prototype;Object.assign(a,{isAliasOf:function(c){if(!(this instanceof Ga&&c instanceof Ga))return!1;var d=this.ia.la.ja,e=this.ia.ka;c.ia=c.ia;var f=c.ia.la.ja;for(c=c.ia.ka;d.pa;)e=d.Aa(e),d=d.pa;for(;f.pa;)c=f.Aa(c),f=f.pa;return d===f&&e===c},clone:function(){this.ia.ka||Ca(this);if(this.ia.za)return this.ia.count.value+=1,this;var c=U,d=Object,e=d.create,f=Object.getPrototypeOf(this),k=this.ia;c=c(e.call(d,f,{ia:{value:{count:k.count,ya:k.ya,za:k.za,ka:k.ka,la:k.la,na:k.na,qa:k.qa}}}));
c.ia.count.value+=1;c.ia.ya=!1;return c},["delete"](){this.ia.ka||Ca(this);if(this.ia.ya&&!this.ia.za)throw new S("Object already scheduled for deletion");Ea(this);var c=this.ia;--c.count.value;0===c.count.value&&(c.na?c.qa.ua(c.na):c.la.ja.ua(c.ka));this.ia.za||(this.ia.na=void 0,this.ia.ka=void 0)},isDeleted:function(){return!this.ia.ka},deleteLater:function(){this.ia.ka||Ca(this);if(this.ia.ya&&!this.ia.za)throw new S("Object already scheduled for deletion");Fa.push(this);this.ia.ya=!0;return this}});
const b=Symbol.dispose;b&&(a[b]=a["delete"])})();
Object.assign(ab.prototype,{La(a){this.Ha&&(a=this.Ha(a));return a},Fa(a){this.ua?.(a)},ta:Va,oa:function(a){function b(){return this.Ca?$a(this.ja.wa,{la:this.Na,ka:c,qa:this,na:a}):$a(this.ja.wa,{la:this,ka:a})}var c=this.La(a);if(!c)return this.Fa(a),null;var d=Ya(this.ja,c);if(void 0!==d){if(0===d.ia.count.value)return d.ia.ka=c,d.ia.na=a,d.clone();d=d.clone();this.Fa(a);return d}d=this.ja.Ka(c);d=Ka[d];if(!d)return b.call(this);d=this.Ba?d.Ia:d.pointerType;var e=Wa(c,this.ja,d.ja);return null===
e?b.call(this):this.Ca?$a(d.ja.wa,{la:d,ka:e,qa:this,na:a}):$a(d.ja.wa,{la:d,ka:e})}});g.noExitRuntime&&(xa=g.noExitRuntime);g.print&&(fa=g.print);g.printErr&&(x=g.printErr);g.wasmBinary&&(B=g.wasmBinary);if(g.preInit)for("function"==typeof g.preInit&&(g.preInit=[g.preInit]);0<g.preInit.length;)g.preInit.shift()();g.ccall=Qb;g.cwrap=(a,b,c,d)=>{var e=!c||c.every(f=>"number"===f||"boolean"===f);return"string"!==b&&e&&!d?g["_"+a]:(...f)=>Qb(a,b,c,f,d)};
g.setValue=function(a,b,c="i8"){c.endsWith("*")&&(c="*");switch(c){case "i1":D[a]=b;break;case "i8":D[a]=b;break;case "i16":F[a>>1]=b;break;case "i32":H[a>>2]=b;break;case "i64":L[a>>3]=BigInt(b);break;case "float":J[a>>2]=b;break;case "double":K[a>>3]=b;break;case "*":I[a>>2]=b;break;default:na(`invalid type for setValue: ${c}`)}};
g.getValue=function(a,b="i8"){b.endsWith("*")&&(b="*");switch(b){case "i1":return D[a];case "i8":return D[a];case "i16":return F[a>>1];case "i32":return H[a>>2];case "i64":return L[a>>3];case "float":return J[a>>2];case "double":return K[a>>3];case "*":return I[a>>2];default:na(`invalid type for getValue: ${b}`)}};
var W,Rb,eb,Sb,Pb,Nb,Ob,M,cb,Tb={u:()=>na(""),h:(a,b,c,d,e)=>{b=N(b);d=0n===d;let f=k=>k;if(d){const k=8*c;f=h=>BigInt.asUintN(k,h);e=f(e)}T(a,{name:b,oa:f,ra:(k,h)=>{"number"==typeof h&&(h=BigInt(h));return h},ta:Ba(b,c,!d),sa:null})},z:(a,b,c,d)=>{b=N(b);T(a,{name:b,oa:function(e){return!!e},ra:function(e,f){return f?c:d},ta:function(e){return this.oa(E[e])},sa:null})},v:(a,b,c,d,e,f,k,h,n,m,l,q,y)=>{l=N(l);f=V(e,f);h&&=V(k,h);m&&=V(n,m);y=V(q,y);var u=Na(l);Ma(u,function(){gb(`Cannot construct ${l} due to unbound types`,
[d])});X([a,b,c],d?[d]:[],v=>{v=v[0];if(d){var z=v.ja;var O=z.wa}else O=Ga.prototype;v=Ja(l,function(...Ha){if(Object.getPrototypeOf(this)!==Ia)throw new S(`Use 'new' to construct ${l}`);if(void 0===A.va)throw new S(`${l} has no accessible constructor`);var ob=A.va[Ha.length];if(void 0===ob)throw new S(`Tried to invoke ctor of ${l} with invalid number of parameters (${Ha.length}) - expected (${Object.keys(A.va).toString()}) parameters instead!`);return ob.apply(this,Ha)});var Ia=Object.create(O,{constructor:{value:v}});
v.prototype=Ia;var A=new Oa(l,v,Ia,y,z,f,h,m);if(A.pa){var P;(P=A.pa).Ea??(P.Ea=[]);A.pa.Ea.push(A)}z=new ab(l,A,!0,!1,!1);P=new ab(l+"*",A,!1,!1,!1);O=new ab(l+" const*",A,!1,!0,!1);Ka[a]={pointerType:P,Ia:O};bb(u,v);return[z,P,O]})},n:(a,b,c,d,e,f)=>{var k=hb(b,c);e=V(d,e);X([],[a],h=>{h=h[0];var n=`constructor ${h.name}`;void 0===h.ja.va&&(h.ja.va=[]);if(void 0!==h.ja.va[b-1])throw new S(`Cannot register multiple constructors with identical number of parameters (${b-1}) for class '${h.name}'! Overload resolution is currently only performed using the parameter count, not actual type info!`);
h.ja.va[b-1]=()=>{gb(`Cannot construct ${h.name} due to unbound types`,k)};X([],k,m=>{m.splice(1,0,null);h.ja.va[b-1]=kb(n,m,null,e,f);return[]});return[]})},b:(a,b,c,d,e,f,k,h,n)=>{var m=hb(c,d);b=N(b);b=lb(b);f=V(e,f);X([],[a],l=>{function q(){gb(`Cannot call ${y} due to unbound types`,m)}l=l[0];var y=`${l.name}.${b}`;b.startsWith("@@")&&(b=Symbol[b.substring(2)]);h&&l.ja.Oa.push(b);var u=l.ja.wa,v=u[b];void 0===v||void 0===v.ma&&v.className!==l.name&&v.xa===c-2?(q.xa=c-2,q.className=l.name,u[b]=
q):(La(u,b,y),u[b].ma[c-2]=q);X([],m,z=>{z=kb(y,z,l,f,k,n);void 0===u[b].ma?(z.xa=c-2,u[b]=z):u[b].ma[c-2]=z;return[]});return[]})},x:a=>T(a,qb),g:(a,b,c)=>{b=N(b);T(a,{name:b,oa:d=>d,ra:(d,e)=>e,ta:rb(b,c),sa:null})},i:(a,b,c,d,e,f,k)=>{var h=hb(b,c);a=N(a);a=lb(a);e=V(d,e);Ma(a,function(){gb(`Cannot call ${a} due to unbound types`,h)},b-1);X([],h,n=>{n=[n[0],null].concat(n.slice(1));bb(a,kb(a,n,null,e,f,k),b-1);return[]})},c:(a,b,c,d,e)=>{b=N(b);let f=h=>h;if(0===d){var k=32-8*c;f=h=>h<<k>>>k;e=
f(e)}T(a,{name:b,oa:f,ra:(h,n)=>n,ta:Ba(b,c,0!==d),sa:null})},a:(a,b,c)=>{function d(f){return new e(D.buffer,I[f+4>>2],I[f>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=N(c);T(a,{name:c,oa:d,ta:d},{Ma:!0})},y:(a,b)=>{b=N(b);T(a,{name:b,oa(c){var d=(d=c+4)?ub.decode(E.subarray(d,vb(E,d,I[c>>2],!0))):"";W(c);return d},ra(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));var e="string"==typeof d;if(!(e||
ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new S("Cannot pass non-string to std::string");var f=e?tb(d):d.length;var k=Rb(4+f+1),h=k+4;I[k>>2]=f;e?sb(d,h,f+1):E.set(d,h);null!==c&&c.push(W,k);return k},ta:Va,sa(c){W(c)}})},d:(a,b,c)=>{c=N(c);if(2===b){var d=xb;var e=yb;var f=zb}else d=Ab,e=Bb,f=Cb;T(a,{name:c,oa:k=>{var h=d(k+4,I[k>>2]*b,!0);W(k);return h},ra:(k,h)=>{if("string"!=typeof h)throw new S(`Cannot pass non-string to C++ string type ${c}`);var n=f(h),m=Rb(4+n+b);I[m>>2]=n/b;e(h,
m+4,n+b);null!==k&&k.push(W,m);return m},ta:Va,sa(k){W(k)}})},j:a=>{T(a,qb)},A:(a,b)=>{b=N(b);T(a,{Ga:!0,name:b,oa:()=>{},ra:()=>{}})},p:()=>{xa=!1;Db=0},f:(a,b,c)=>{var [d,...e]=Gb(a,b);b=d.ra.bind(d);var f=e.map(n=>n.ta.bind(n));a--;var k={toValue:pb};a=f.map((n,m)=>{var l=`argFromPtr${m}`;k[l]=n;return`${l}(args${m?"+"+8*m:""})`});switch(c){case 0:var h="toValue(handle)";break;case 2:h="new (toValue(handle))";break;case 3:h="";break;case 1:k.getStringOrSymbol=Jb,h="toValue(handle)[getStringOrSymbol(methodName)]"}h+=
`(${a})`;d.Ga||(k.toReturnWire=b,k.emval_returnValue=Hb,h=`return emval_returnValue(toReturnWire, destructorsRef, ${h})`);h=`return function (handle, methodName, destructorsRef, args) {\n  ${h}\n  }`;c=(new Function(Object.keys(k),h))(...Object.values(k));h=`methodCaller<(${e.map(n=>n.name)}) => ${d.name}>`;return Fb(Ja(h,c))},k:nb,l:a=>{9<a&&(Y[a+1]+=1)},e:(a,b,c,d,e)=>Eb[a](b,c,d,e),m:a=>{var b=pb(a);ib(b);nb(a)},q:(a,b)=>{Z[a]&&(clearTimeout(Z[a].id),delete Z[a]);if(!b)return 0;var c=setTimeout(()=>
{delete Z[a];Lb(()=>Sb(a,performance.now()))},b);Z[a]={id:c,Sa:b};return 0},w:a=>{var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-M.buffer.byteLength+65535)/65536|0;try{M.grow(d);ma();var e=1;break a}catch(f){}e=void 0}if(e)return!0}return!1},t:()=>52,r:function(){return 70},s:(a,b,c,d)=>{for(var e=0,f=0;f<c;f++){var k=I[b>>2],h=I[b+4>>2];b+=8;for(var n=0;n<h;n++){var m=
a,l=E[k+n],q=Mb[m];0===l||10===l?(m=1===m?fa:x,l=vb(q,0),l=ub.decode(q.buffer?q.subarray(0,l):new Uint8Array(q.slice(0,l))),m(l),q.length=0):q.push(l)}e+=h}I[d>>2]=e;return 0},o:Kb},Ub;
Ub=await (async function(){function a(c){c=Ub=c.exports;W=g._free=c.D;Rb=g._malloc=c.E;g._tvg_engine_init=c.F;g._tvg_engine_term=c.G;g._tvg_swcanvas_create=c.H;g._tvg_canvas_destroy=c.I;g._tvg_swcanvas_set_target=c.J;g._tvg_canvas_push=c.K;g._tvg_canvas_push_at=c.L;g._tvg_canvas_remove=c.M;g._tvg_canvas_update=c.N;g._tvg_canvas_draw=c.O;g._tvg_canvas_sync=c.P;g._tvg_paint_set_transform=c.Q;g._tvg_paint_get_transform=c.R;g._tvg_paint_set_opacity=c.S;g._tvg_shape_new=c.T;g._tvg_shape_reset=
c.U;g._tvg_shape_append_rect=c.V;g._tvg_shape_append_circle=c.W;g._tvg_shape_set_stroke_width=c.X;g._tvg_shape_set_stroke_color=c.Y;g._tvg_shape_set_fill_color=c.Z;g._tvg_scene_new=c._;g._tvg_scene_push=c.$;g._tvg_scene_push_at=c.aa;g._tvg_scene_remove=c.ba;eb=c.ca;Sb=c.da;Pb=c.fa;Nb=c.ga;Ob=c.ha;M=c.B;cb=c.ea;ma();return Ub}var b={a:Tb};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});oa??=g.locateFile?g.locateFile?g.locateFile("thorvg.wasm",r):r+"thorvg.wasm":
(new URL("thorvg.wasm",import.meta.url)).href;return a((await ra(b)).instance)}());
(function(){function a(){g.calledRun=!0;if(!C){la=!0;Ub.C();ia?.(g);g.onRuntimeInitialized?.();if(g.postRun)for("function"==typeof g.postRun&&(g.postRun=[g.postRun]);g.postRun.length;){var b=g.postRun.shift();ua.push(b)}ta(ua)}}if(g.preRun)for("function"==typeof g.preRun&&(g.preRun=[g.preRun]);g.preRun.length;)wa();ta(va);g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);a()},1)):a()})();la?moduleRtn=g:moduleRtn=new Promise((a,b)=>{ia=a;ja=b});
;return moduleRtn}export default Module;
