name: Build

on:
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"
          cache: "pnpm"

      - name: Install Dependencies
        run: pnpm install

      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: "4.0.17"
          actions-cache-folder: "emsdk-cache"

      - name: Verify Emscripten Setup
        run: |
          source $EMSDK/emsdk_env.sh
          which emcc
          emcc --version
          echo "EMSDK=$EMSDK" >> $GITHUB_ENV

      - name: Install Meson and Ninja
        run: pip3 install meson ninja

      - name: Build Packages
        run: pnpm build
